"""
Script para crear habitaciones de demostración
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sistema_alojamiento.settings')
django.setup()

from app.habitaciones.models import Habitacion
from decimal import Decimal

def crear_habitaciones_demo():
    # Verificar habitaciones existentes
    count_existente = Habitacion.objects.count()
    print(f"Habitaciones existentes: {count_existente}")
    
    # Si ya hay habitaciones, preguntar si desea agregar más
    if count_existente >= 10:
        print("Ya hay suficientes habitaciones de demostración.")
        return
    
    habitaciones_demo = [
        {
            'numero': '101',
            'nombre': 'Habitación Simple Económica',
            'tipo': 'simple',
            'capacidad': 1,
            'precio_noche': Decimal('45.00'),
            'precio_fin_semana': Decimal('55.00'),
            'estado': 'disponible',
            'piso': 1,
            'descripcion': 'Habitación simple perfecta para viajeros solitarios',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'interior',
            'numero_camas': 1,
            'tipo_cama': 'single',
            'reserva_min_noches': 1,
            'reserva_max_noches': 30,
            'permite_mascotas': False,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': False,
            'aire_acondicionado': False,
            'calefaccion': True,
            'minibar': False,
            'caja_fuerte': False,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': False,
        },
        {
            'numero': '201',
            'nombre': 'Habitación Doble Estándar',
            'tipo': 'doble',
            'capacidad': 2,
            'precio_noche': Decimal('75.00'),
            'precio_fin_semana': Decimal('95.00'),
            'estado': 'disponible',
            'piso': 2,
            'descripcion': 'Habitación doble cómoda con todas las comodidades básicas',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'ciudad',
            'numero_camas': 1,
            'tipo_cama': 'queen',
            'reserva_min_noches': 1,
            'reserva_max_noches': 30,
            'permite_mascotas': False,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': True,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': False,
            'caja_fuerte': True,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': True,
        },
        {
            'numero': '301',
            'nombre': 'Suite Deluxe Vista al Mar',
            'tipo': 'deluxe',
            'capacidad': 3,
            'precio_noche': Decimal('150.00'),
            'precio_fin_semana': Decimal('180.00'),
            'estado': 'disponible',
            'piso': 3,
            'descripcion': 'Amplia suite con vista espectacular al mar y todas las amenidades premium',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'mar',
            'numero_camas': 2,
            'tipo_cama': 'king',
            'reserva_min_noches': 2,
            'reserva_max_noches': 30,
            'permite_mascotas': True,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': True,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': True,
            'caja_fuerte': True,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': True,
        },
        {
            'numero': '102',
            'nombre': 'Habitación Triple Familiar',
            'tipo': 'triple',
            'capacidad': 3,
            'precio_noche': Decimal('95.00'),
            'precio_fin_semana': Decimal('115.00'),
            'estado': 'disponible',
            'piso': 1,
            'descripcion': 'Habitación espaciosa ideal para familias pequeñas',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'jardin',
            'numero_camas': 3,
            'tipo_cama': 'mixta',
            'reserva_min_noches': 1,
            'reserva_max_noches': 30,
            'permite_mascotas': True,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': True,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': False,
            'caja_fuerte': True,
            'escritorio': False,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': False,
        },
        {
            'numero': '401',
            'nombre': 'Suite Presidencial Luxury',
            'tipo': 'presidencial',
            'capacidad': 4,
            'precio_noche': Decimal('250.00'),
            'precio_fin_semana': Decimal('300.00'),
            'estado': 'disponible',
            'piso': 4,
            'descripcion': 'La mejor habitación del hotel con todas las comodidades de lujo',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'mar',
            'numero_camas': 2,
            'tipo_cama': 'king',
            'reserva_min_noches': 3,
            'reserva_max_noches': 30,
            'permite_mascotas': True,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': True,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': True,
            'caja_fuerte': True,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': True,
        },
        {
            'numero': '202',
            'nombre': 'Habitación Doble Económica',
            'tipo': 'doble',
            'capacidad': 2,
            'precio_noche': Decimal('65.00'),
            'precio_fin_semana': Decimal('80.00'),
            'estado': 'limpieza',
            'piso': 2,
            'descripcion': 'Habitación doble con buen precio',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'interior',
            'numero_camas': 2,
            'tipo_cama': 'single',
            'reserva_min_noches': 1,
            'reserva_max_noches': 30,
            'permite_mascotas': False,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': False,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': False,
            'caja_fuerte': False,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': False,
            'secador_cabello': False,
        },
        {
            'numero': '302',
            'nombre': 'Suite Vista Jardín',
            'tipo': 'suite',
            'capacidad': 2,
            'precio_noche': Decimal('120.00'),
            'precio_fin_semana': Decimal('145.00'),
            'estado': 'ocupada',
            'piso': 3,
            'descripcion': 'Suite elegante con hermosa vista al jardín',
            'tipo_bano': 'privado',
            'bano_privado': True,
            'vista': 'jardin',
            'numero_camas': 1,
            'tipo_cama': 'king',
            'reserva_min_noches': 2,
            'reserva_max_noches': 30,
            'permite_mascotas': False,
            'permite_fumar': False,
            'tv': True,
            'internet': True,
            'acceso_youtube': True,
            'aire_acondicionado': True,
            'calefaccion': True,
            'minibar': True,
            'caja_fuerte': True,
            'escritorio': True,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': True,
            'secador_cabello': True,
        },
        {
            'numero': '103',
            'nombre': 'Habitación Simple Compartida',
            'tipo': 'simple',
            'capacidad': 1,
            'precio_noche': Decimal('35.00'),
            'estado': 'disponible',
            'piso': 1,
            'descripcion': 'Habitación simple económica con baño compartido',
            'tipo_bano': 'compartido',
            'bano_privado': False,
            'vista': 'interior',
            'numero_camas': 1,
            'tipo_cama': 'single',
            'reserva_min_noches': 1,
            'reserva_max_noches': 15,
            'permite_mascotas': False,
            'permite_fumar': False,
            'tv': False,
            'internet': True,
            'acceso_youtube': False,
            'aire_acondicionado': False,
            'calefaccion': True,
            'minibar': False,
            'caja_fuerte': False,
            'escritorio': False,
            'armario': True,
            'agua_caliente': True,
            'toallas': True,
            'papel_higienico': True,
            'shampoo': False,
            'secador_cabello': False,
        },
    ]
    
    creadas = 0
    for hab_data in habitaciones_demo:
        # Verificar si ya existe una habitación con ese número
        if not Habitacion.objects.filter(numero=hab_data['numero']).exists():
            try:
                Habitacion.objects.create(**hab_data)
                print(f"✓ Habitación {hab_data['numero']} - {hab_data['nombre']} creada")
                creadas += 1
            except Exception as e:
                print(f"✗ Error al crear habitación {hab_data['numero']}: {e}")
        else:
            print(f"- Habitación {hab_data['numero']} ya existe")
    
    total = Habitacion.objects.count()
    print(f"\n{'='*60}")
    print(f"Habitaciones creadas: {creadas}")
    print(f"Total de habitaciones en BD: {total}")
    print(f"{'='*60}")

if __name__ == '__main__':
    crear_habitaciones_demo()
