# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del bloqueo')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del bloqueo')),
                ('razon', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('limpieza_profunda', 'Limpieza Profunda'), ('renovacion', 'Renovación'), ('problema', 'Problema Técnico'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles del bloqueo', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(help_text='Habitación bloqueada', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Bloqueo de Habitación',
                'verbose_name_plural': 'Bloqueos de Habitaciones',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia')], default='preventivo', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del problema o tarea de mantenimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización', null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, help_text='Costo del mantenimiento', max_digits=10)),
                ('notas_resolucion', models.TextField(blank=True, help_text='Acción tomada para resolver el problema', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Técnico responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(help_text='Habitación a mantener', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TareaLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(help_text='Fecha programada para la limpieza')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio de la limpieza', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de finalización de la limpieza', null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Notas especiales para la limpieza', null=True)),
                ('notas_completa', models.TextField(blank=True, help_text='Observaciones de cómo quedó la habitación', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Empleado responsable de la limpieza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_limpieza', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(help_text='Habitación a limpiar', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_limpieza', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Tarea de Limpieza',
                'verbose_name_plural': 'Tareas de Limpieza',
                'ordering': ['fecha_programada', '-prioridad'],
            },
        ),
    ]
