# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('ci', 'Cédula de Identidad'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC'), ('otro', 'Otro')], default='ci', max_length=20)),
                ('numero_documento', models.CharField(help_text='CI, Pasaporte o RUC', max_length=50, unique=True)),
                ('telefono', models.CharField(help_text='Número con código de país (+58...)', max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-\\+\\s]+$', 'Ingrese un teléfono válido')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(choices=[('VE', 'Venezuela'), ('CO', 'Colombia'), ('PE', 'Perú'), ('EC', 'Ecuador'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('MX', 'México'), ('OTRO', 'Otro país')], default='VE', help_text='País de origen del cliente', max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indicar si el cliente está activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
