# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_nueva_reserva', models.BooleanField(default=True, help_text='Notificar cuando hay nueva reserva')),
                ('notificar_cambio_reserva', models.BooleanField(default=True, help_text='Notificar cambios en reservas')),
                ('notificar_cancelacion_reserva', models.BooleanField(default=True, help_text='Notificar cuando se cancela una reserva')),
                ('notificar_pago_pendiente', models.BooleanField(default=True, help_text='Notificar pagos pendientes')),
                ('notificar_pago_recibido', models.BooleanField(default=True, help_text='Notificar cuando se recibe pago')),
                ('notificar_check_in', models.BooleanField(default=True, help_text='Notificar check-in')),
                ('notificar_check_out', models.BooleanField(default=True, help_text='Notificar check-out')),
                ('recibir_por_email', models.BooleanField(default=False, help_text='Recibir notificaciones por correo electrónico')),
                ('hora_inicio_notificaciones', models.TimeField(default='08:00', help_text='Hora de inicio para enviar notificaciones')),
                ('hora_fin_notificaciones', models.TimeField(default='22:00', help_text='Hora de fin para enviar notificaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('intento', models.PositiveIntegerField(default=0, help_text='Número de intentos de envío')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, help_text='Fecha y hora de envío', null=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Historial de Email',
                'verbose_name_plural': 'Historial de Emails',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva_nueva', 'Nueva Reserva'), ('reserva_confirmada', 'Reserva Confirmada'), ('reserva_cancelada', 'Reserva Cancelada'), ('pago_pendiente', 'Pago Pendiente'), ('pago_recibido', 'Pago Recibido'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('sistema', 'Notificación del Sistema')], help_text='Tipo de notificación', max_length=50)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje de la notificación')),
                ('estado', models.CharField(choices=[('no_leida', 'No Leída'), ('leida', 'Leída'), ('archivada', 'Archivada')], default='no_leida', max_length=20)),
                ('url_accion', models.URLField(blank=True, help_text='URL para accionar la notificación', null=True)),
                ('leida_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(blank=True, help_text='Pago relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='pagos.pago')),
                ('reserva', models.ForeignKey(blank=True, help_text='Reserva relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='reservas.reserva')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['usuario', '-creado'], name='notificacio_usuario_a2dadc_idx'), models.Index(fields=['estado', 'usuario'], name='notificacio_estado_e23456_idx')],
            },
        ),
    ]
