# Generated by Django 5.1.1 on 2026-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(default='Sistema de Alojamiento', help_text='Nombre del hotel', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del hotel')),
                ('email', models.EmailField(help_text='Correo de contacto', max_length=254)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp', max_length=20, null=True)),
                ('direccion', models.TextField(help_text='Dirección física del hotel')),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para Google Maps', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para Google Maps', max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo del hotel', null=True, upload_to='sitio/logo/')),
                ('foto_principal', models.ImageField(blank=True, help_text='Foto principal del hotel', null=True, upload_to='sitio/fotos/')),
                ('redes_sociales', models.JSONField(blank=True, default=dict, help_text='Enlaces a redes sociales (Facebook, Instagram, etc)')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('exterior', 'Exterior'), ('lobby', 'Lobby/Recepción'), ('habitaciones', 'Habitaciones'), ('restaurante', 'Restaurante'), ('piscina', 'Piscina'), ('eventos', 'Eventos'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('foto', models.ImageField(upload_to='galeria/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['categoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cancelacion', 'Política de Cancelación'), ('checkin', 'Política de Check-in'), ('checkout', 'Política de Check-out'), ('ninos', 'Política de Niños'), ('mascotas', 'Política de Mascotas'), ('general', 'Términos y Condiciones')], max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='fas fa-star', help_text='Clase de Font Awesome (ej: fas fa-wifi)', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el sitio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('titulo', models.CharField(help_text='Título del testimonio', max_length=200)),
                ('contenido', models.TextField()),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Calificación de 1 a 5 estrellas')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/fotos/')),
                ('aprobado', models.BooleanField(default=False, help_text='Mostrar testimonio en el sitio público')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-creado'],
            },
        ),
    ]
