# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], help_text='Período de la estadística', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha de la estadística')),
                ('total_reservas', models.PositiveIntegerField(default=0, help_text='Total de reservas')),
                ('reservas_confirmadas', models.PositiveIntegerField(default=0, help_text='Reservas confirmadas')),
                ('reservas_canceladas', models.PositiveIntegerField(default=0, help_text='Reservas canceladas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos totales', max_digits=12)),
                ('porcentaje_ocupacion', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ocupación', max_digits=5)),
                ('clientes_nuevos', models.PositiveIntegerField(default=0, help_text='Clientes nuevos')),
                ('notas', models.TextField(blank=True, help_text='Notas especiales', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ingresos_reservas', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos de reservas', max_digits=12)),
                ('ingresos_adicionales', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos adicionales (servicios extra, etc)', max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos totales', max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, help_text='Gastos (mantenimiento, etc)', max_digits=12)),
                ('ganancia_neta', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia neta', max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Ingresos',
                'verbose_name_plural': 'Reportes de Ingresos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReporteClientesFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reservas', models.PositiveIntegerField(default=0, help_text='Total de reservas realizadas')),
                ('total_noches', models.PositiveIntegerField(default=0, help_text='Total de noches hospedadas')),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0, help_text='Gasto total en reservas', max_digits=12)),
                ('fecha_primera_reserva', models.DateField(blank=True, help_text='Fecha de la primera reserva', null=True)),
                ('fecha_ultima_reserva', models.DateField(blank=True, help_text='Fecha de la última reserva', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_frecuencia', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cliente Frecuente',
                'verbose_name_plural': 'Clientes Frecuentes',
                'ordering': ['-total_reservas'],
            },
        ),
        migrations.CreateModel(
            name='ReporteOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha del reporte')),
                ('ocupada', models.BooleanField(default=False, help_text='Si la habitación está ocupada')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que ocupa la habitación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ocupacion', to='habitaciones.habitacion')),
                ('reserva', models.ForeignKey(blank=True, help_text='Reserva asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reporte de Ocupación',
                'verbose_name_plural': 'Reportes de Ocupación',
                'ordering': ['-fecha', 'habitacion'],
            },
        ),
    ]
