# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(help_text='Fecha de check-in')),
                ('fecha_salida', models.DateField(help_text='Fecha de check-out')),
                ('num_huespedes', models.PositiveIntegerField(default=1, help_text='Número de huéspedes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('no_show', 'No presentado')], default='pendiente', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar (calculado automáticamente)', max_digits=12)),
                ('notas', models.TextField(blank=True, help_text='Notas especiales de la reserva', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clientes.cliente')),
                ('habitacion', models.ForeignKey(help_text='Habitación reservada', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=255)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reservas.reserva')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
