# Generated by Django 5.1.1 on 2026-04-07 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_realizado',
            field=models.BooleanField(default=False, help_text='Indica si se realizó el check-in'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkout_realizado',
            field=models.BooleanField(default=False, help_text='Indica si se realizó el check-out'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_checkin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real del check-in', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_checkout',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real del check-out', null=True),
        ),
        migrations.CreateModel(
            name='AcompananteReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(choices=[('ci', 'Cédula'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='ci', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
                'ordering': ['-creado'],
            },
        ),
    ]
