# Generated by Django 5.1.1 on 2026-04-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_checkin_realizado_reserva_checkout_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('online', 'En línea'), ('presencial', 'Presencial')], default='online', help_text='Canal/origen de la reserva (en línea o presencial)', max_length=20),
        ),
    ]
