# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito/Débito')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='efectivo', help_text='Método de pago utilizado', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del pago')),
                ('comprobante', models.FileField(blank=True, help_text='Comprobante de pago (factura, recibo, etc)', null=True, upload_to='pagos/comprobantes/%Y/%m/')),
                ('referencia', models.CharField(blank=True, help_text='Referencia de transferencia o número de autorización', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del pago', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(help_text='Reserva asociada al pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
