# Generated by Django 5.1.1 on 2026-02-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(help_text='Código QR o datos para generar el QR (puede ser URL, número de cuenta, etc)', max_length=255)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del método de pago (ej: Transferencia a cuenta 123456)', max_length=200)),
                ('imagen_qr', models.ImageField(blank=True, help_text='Imagen del código QR', null=True, upload_to='qr_codes/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración QR',
                'verbose_name_plural': 'Configuraciones QR',
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
        migrations.AddField(
            model_name='pago',
            name='comentario_validacion',
            field=models.TextField(blank=True, help_text='Comentarios o razón de rechazo', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_cliente',
            field=models.ImageField(blank=True, help_text='Comprobante de transferencia enviado por cliente', null=True, upload_to='pagos/comprobantes_cliente/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de validación del pago', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_transaccion',
            field=models.CharField(blank=True, help_text='Referencia de transferencia o número de confirmación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Recepcionista que validó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de pago validado', null=True, upload_to='pagos/comprobantes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Comprobante Enviado'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='qr', help_text='Método de pago utilizado', max_length=20),
        ),
    ]
