# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('cliente', 'Cliente'), ('gerente', 'Gerente'), ('empleado_limpieza', 'Empleado de Limpieza')], max_length=50, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción de los permisos y responsabilidades del rol')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('actualizar', 'Actualizar')], max_length=20)),
                ('modelo', models.CharField(blank=True, help_text='Modelo afectado por la actividad', max_length=100, null=True)),
                ('id_objeto', models.PositiveIntegerField(blank=True, help_text='ID del objeto modificado', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\-\\+\\s]+$', 'Ingrese un teléfono válido')])),
                ('celular', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\-\\+\\s]+$', 'Ingrese un celular válido')])),
                ('cedula', models.CharField(blank=True, help_text='Cédula de identidad del empleado', max_length=50, null=True, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='usuarios/fotos/%Y/%m/')),
                ('activo', models.BooleanField(default=True, help_text='Indicar si el usuario está activo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, help_text='Fecha de ingreso al sistema')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario del sistema', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(help_text='Rol del usuario en el sistema', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='autenticacion.rol')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
