# Generated by Django 5.1.1 on 2026-02-08 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de la habitación', max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('simple', 'Habitación Simple'), ('doble', 'Habitación Doble'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('presidencial', 'Suite Presidencial')], default='doble', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=2, help_text='Número máximo de personas', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_noche', models.DecimalField(decimal_places=2, help_text='Precio por noche en $', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En limpieza'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la habitación', null=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto principal de la habitación', null=True, upload_to='habitaciones/%Y/%m/')),
                ('piso', models.PositiveIntegerField(default=1, help_text='Número del piso')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='FotoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='habitaciones/galeria/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AmenidadHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidades', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
            },
        ),
    ]
