# Generated by Cascade on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='tipo_bano',
            field=models.CharField(choices=[('privado', 'Baño privado'), ('compartido', 'Baño compartido'), ('sin_bano', 'Sin baño')], default='privado', max_length=20),
        ),
        migrations.AddField(model_name='habitacion', name='tv', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='internet', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='acceso_youtube', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='aire_acondicionado', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='calefaccion', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='minibar', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='caja_fuerte', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='escritorio', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='armario', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='agua_caliente', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='toallas', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='papel_higienico', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='habitacion', name='shampoo', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='secador_cabello', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='habitacion', name='vista', field=models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField(model_name='habitacion', name='youtube_url', field=models.URLField(blank=True, null=True)),
    ]
