# Generated by Cascade on 2026-02-08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitacion_campos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En limpieza'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(default='', help_text='Nombre comercial de la habitación (ej: Habitación Doble Deluxe)', max_length=100),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='bano_privado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='vista',
            field=models.CharField(choices=[('mar', 'Mar'), ('ciudad', 'Ciudad'), ('jardin', 'Jardín'), ('montana', 'Montaña'), ('interior', 'Interior'), ('sin_vista', 'Sin vista')], default='sin_vista', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numero_camas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_cama',
            field=models.CharField(choices=[('single', 'Single'), ('queen', 'Queen'), ('king', 'King'), ('mixta', 'Mixta')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='reserva_min_noches',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='reserva_max_noches',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='permite_mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='permite_fumar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio_fin_semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
