# Generated by Django 4.2.7 on 2026-03-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_formulario_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Habitación Simple'), ('doble', 'Habitación Doble'), ('triple', 'Habitación Triple'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('presidencial', 'Suite Presidencial')], default='doble', max_length=20),
        ),
    ]
